CREATE DATABASE `online-estore`
USE `online-estore`;

/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.1 		*/
/*  Created On : 16-Aug-2020 3:04:52 PM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
;
/* Drop Tables */

DROP TABLE IF EXISTS `bundle_deal` CASCADE
;

DROP TABLE IF EXISTS `discount_deal` CASCADE
;

DROP TABLE IF EXISTS `product` CASCADE
;

DROP TABLE IF EXISTS `user` CASCADE
;

/* Create Tables */

CREATE TABLE `bundle_deal`
(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `product_id` INT UNSIGNED NOT NULL,
    `bundle_product_id` INT UNSIGNED NOT NULL,
    CONSTRAINT `PK_bundle_deal` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `discount_deal`
(
    `product_id` INT UNSIGNED NULL,
    `discount_rate` DECIMAL(10,2) UNSIGNED NULL
)

;

CREATE TABLE `product`
(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(50) NOT NULL,
    `description` VARCHAR(50) NOT NULL,
    `status` INT UNSIGNED NULL COMMENT '0: disabled, 1: enabled',
    `price` DECIMAL(32,2) NOT NULL,
    `quantity` INT UNSIGNED NOT NULL,
    CONSTRAINT `PK_product_id` PRIMARY KEY (`id` ASC)
)

;

CREATE TABLE `user`
(
    `id` INT NOT NULL,
    `name` VARCHAR(50) NULL,
    CONSTRAINT `PK_user` PRIMARY KEY (`id` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `bundle_deal`
    ADD CONSTRAINT `UNIQUE_product_bundle_product_id` UNIQUE (`product_id` ASC, `bundle_product_id` ASC)
;

ALTER TABLE `bundle_deal`
    ADD INDEX `IXFK_bundle_deal_bundle_product` (`bundle_product_id` ASC)
;

ALTER TABLE `bundle_deal`
    ADD INDEX `IXFK_bundle_deal_product` (`product_id` ASC)
;

ALTER TABLE `discount_deal`
    ADD CONSTRAINT `UNIQUE_product_id_discount_rate` UNIQUE (`product_id` ASC, `discount_rate` ASC)
;

ALTER TABLE `discount_deal`
    ADD INDEX `IXFK_discount_deal_product` (`product_id` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `bundle_deal`
    ADD CONSTRAINT `FK_bundle_deal_bundle_product`
        FOREIGN KEY (`bundle_product_id`) REFERENCES `product` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `bundle_deal`
    ADD CONSTRAINT `FK_bundle_deal_product`
        FOREIGN KEY (`product_id`) REFERENCES `product` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `discount_deal`
    ADD CONSTRAINT `FK_discount_deal_product`
        FOREIGN KEY (`product_id`) REFERENCES `product` (`id`) ON DELETE Restrict ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
;


insert into `online-estore`.user values (1, 'alan');
INSERT INTO `online-estore`.product (name, description, status, price, quantity) VALUES ('Lenovo X230', 'A solid laptop with nice water proof keyboard', 1, 6500.00,    1);
INSERT INTO `online-estore`.product (name, description, status, price, quantity) VALUES ('Mouse', 'A general Mouse for bundle deal', 1, 10.00, 0);
;
